package org.generationcp.middleware.pojos.workbench;

import java.util.Arrays;
import java.util.List;

public enum PermissionsEnum {
	ADMIN,
	ADMINISTRATION,
	CROP_MANAGEMENT,
	BREEDING_ACTIVITIES,
	INFORMATION_MANAGEMENT,
	STATISTICAL_ANALYSIS,
	SITE_ADMIN,
	MANAGE_ONTOLOGIES,
	IMPORT_GERMPLASM,
	MANAGE_GENOTYPING_DATA,
	MANAGE_PROGRAMS,
	ADD_PROGRAM,
	MANAGE_PROGRAM_SETTINGS,
	MANAGE_GERMPLASM,
	MANAGE_SAMPLES,
	MANAGE_STUDIES,
	BROWSE_STUDIES,
	HEAD_TO_HEAD_QUERY,
	MULTI_TRAIT_QUERY,
	IMPORT_DATASETS,
	SINGLE_SITE_ANALYSIS,
	MULTI_SITE_ANALYSIS,
	MANAGE_INVENTORY,
	MANAGE_LOTS,
	LOT_LABEL_PRINTING;

	public static final String HAS_INVENTORY_VIEW = " or hasAnyAuthority('ADMIN'"
		+ ",'CROP_MANAGEMENT'"
		+ ",'MANAGE_INVENTORY'"
		+ ",'MANAGE_LOTS'"
		+ ",'MANAGE_TRANSACTIONS'"
		+ ",'VIEW_LOTS'"
		+ ",'VIEW_TRANSACTIONS')";

	public static final String HAS_PREPARE_PLANTING = " or hasAnyAuthority('ADMIN'"
		+ ", 'BREEDING_ACTIVITIES'"
		+ ", 'MANAGE_STUDIES'"
		+ ", 'MS_MANAGE_OBSERVATION_UNITS'"
		+ ", 'MS_WITHDRAW_INVENTORY'"
		+ ", 'MS_CREATE_PENDING_WITHDRAWALS'"
		+ ", 'MS_MANAGE_OBSERVATION_UNITS'"
		+ ", 'MS_CREATE_CONFIRMED_WITHDRAWALS')";

	public static final String HAS_CREATE_LOTS_BATCH = " or hasAnyAuthority('ADMIN'"
		+ ", 'BREEDING_ACTIVITIES'"
		+ ", 'MANAGE_GERMPLASM'"
		+ ", 'MG_MANAGE_INVENTORY'"
		+ ", 'MG_CREATE_LOTS'"
		+ ", 'CREATE_LOTS')";

	public static final List<String> SITE_ADMIN_PERMISSIONS = Arrays.asList(SITE_ADMIN.name(), ADMINISTRATION.name(), ADMIN.name());
}
