package org.generationcp.middleware.domain.workbench;

public enum Authority {

	ADMIN,
	ADMINISTRATION,
	CROP_MANAGEMENT,
	BREEDING_ACTIVITIES,
	INFORMATION_MANAGEMENT,
	STATISTICAL_ANALYSIS,
	SITE_ADMIN,
	MANAGE_ONTOLOGIES,
	IMPORT_GERMPLASM,
	MANAGE_GENOTYPING_DATA,
	MANAGE_PROGRAMS,
	ADD_PROGRAM,
	MANAGE_PROGRAM_SETTINGS,
	MANAGE_GERMPLASM,
	MANAGE_SAMPLES,
	MANAGE_STUDIES,
	BROWSE_STUDIES,
	HEAD_TO_HEAD_QUERY,
	MULTI_TRAIT_QUERY,
	IMPORT_DATASETS,
	SINGLE_SITE_ANALYSIS,
	MULTI_SITE_ANALYSIS

}
